# Site settings
title: "Spencer's Portfolio"
email: "spencershadley@utexas.edu"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "spencer-shadley.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: spencer-shadley

# Build settings
markdown: kramdown
