# Site settings
title: "Spencer's Portfolio"
email: 'sshadley.dev@gmail.com'
email_subject: 'Software Development Job Opportunity'
description: > # this means to ignore newlines until "baseurl:"
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'spencer-shadley.github.io' # the base hostname & protocol for your site

linkedin_username: spencershadley
github_username: spencer-shadley

# Build settings
markdown: kramdown
